WorkerDataGeneral.h: Fix clang compile error
clang won't implicitly convert from a bool to an enum, do it explciitly
with int().

../../include/WorkerDataGeneral.h:526:12: error: no matching conversion for static_cast from 'std::__1::bitset<32>::const_reference' (aka '__bit_const_reference<std::__1::__bitset<1, 32> >') to 'Sex::sex_type'